# appveyor.yml
install:
  - set PATH=C:\Projects\tsukasa\system;C:\Projects\tsukasa;C:\Ruby22\bin;%PATH%
  - set APPVEYOR_BUILD=true
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake spec
  